// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/wasl-auth-journey/InteractiveFlow.tsx": () => import("../components/mockups/wasl-auth-journey/InteractiveFlow.tsx"),
  "./components/mockups/wasl-auth-journey/JourneyMap.tsx": () => import("../components/mockups/wasl-auth-journey/JourneyMap.tsx")
};
