import React, {useState} from "react";
import "./_group.css";

type Role = "Circle Lead"|"Amanah Partner"|"Nurse / Professional"|"Companion";
const roles: {name:Role;desc:string;detail:string}[] = [
  {name:"Circle Lead",desc:"I am the older adult receiving care.",detail:"You decide what matters and who helps."},
  {name:"Amanah Partner",desc:"Family or trusted person.",detail:"You coordinate with care and permission."},
  {name:"Nurse / Professional",desc:"A nurse or care professional.",detail:"You see assigned tasks, never a whole life."},
  {name:"Companion",desc:"Community helper.",detail:"You offer practical, human support."},
];
const screens = ["Language","Welcome","Account","Role","Circle","You","Preferences","Safety","Notifications","Review"];
export function InteractiveFlow() {
  const [screen,setScreen]=useState(0); const [mode,setMode]=useState<"signin"|"signup"|null>(null); const [role,setRole]=useState<Role>("Circle Lead"); const [lang,setLang]=useState("English"); const [large,setLarge]=useState(false); const [circle,setCircle]=useState("The Rahman Circle"); const [done,setDone]=useState(false);
  const go=(n:number)=>setScreen(Math.max(0,Math.min(9,n)));
  const title = screen===0?"Welcome to Wasl":screens[screen];
  if(done) return <div className="wasl-journey w-proto-shell"><Phone><div className="w-success"><div className="w-success-mark">✓</div><img src="/__mockup/images/wasl-logo.png" alt="Wasl"/><p className="w-kicker">A MOMENT TO CELEBRATE</p><h1>Your Wasl Circle<br/><em>is ready.</em></h1><p>Wasl will help your trusted people coordinate care, without taking your voice away.</p><div className="w-orient"><button onClick={()=>setDone(false)}>Talk to Wasl <span>→</span></button><button onClick={()=>setDone(false)}>Invite / meet your circle <span>→</span></button></div><button className="w-primary" onClick={()=>{setDone(false);go(0)}}>Go to Home</button></div></Phone></div>;
  return <div className={`wasl-journey w-proto-shell ${large?"w-large":""}`}><Phone>
    <div className="w-proto-top"><button className="w-back" onClick={()=>go(screen-1)} disabled={screen===0}>← <span>Back</span></button><img src="/__mockup/images/wasl-logo.png" alt="Wasl"/><button className="w-help">?</button></div>
    <div className="w-progress"><span style={{width:`${Math.max(8,screen*11)}%`}}/><small>{screen===0?"First hello":`Step ${screen} of 9`}</small></div>
    {screen===0&&<div className="w-screen w-launch"><div className="w-mark"><img src="/__mockup/images/wasl-logo.png" alt="Wasl"/></div><p className="w-kicker">A PRIVATE CIRCLE FOR CARE</p><h1>Welcome to<br/><em>Wasl.</em></h1><p>Care coordination that respects your culture, your privacy, and your pace.</p><div className="w-access"><select value={lang} onChange={e=>setLang(e.target.value)}><option>English</option><option>Français</option><option>العربية</option><option>فارسی</option></select><button onClick={()=>setLarge(!large)}>{large?"A−":"A+"} Larger text</button><button>◌ Voice guidance</button></div><div className="w-action-stack"><button className="w-primary" onClick={()=>{setMode("signin");go(1)}}>Sign in</button><button className="w-secondary" onClick={()=>{setMode("signup");go(1)}}>Create account</button></div><p className="w-fine">Your care information stays yours. Wasl coordinates reminders and people; it does not provide medical advice or emergency response.</p></div>}
    {screen===1&&<div className="w-screen"><p className="w-kicker">{mode==="signin"?"WELCOME BACK":"A GENTLE START"}</p><h1>{mode==="signin"?"Good to see you again.":"Let’s make your circle."}</h1><p>{mode==="signin"?"Sign in with your phone, or choose another way.":"We’ll save your progress so you can return whenever you’re ready."}</p><label>Mobile number<input placeholder="+1 555 014 2086"/></label><button className="w-primary" onClick={()=>go(mode==="signin"?2:2)}>{mode==="signin"?"Send verification code":"Continue with phone"} <span>→</span></button><button className="w-link" onClick={()=>go(2)}>{mode==="signin"?"Use email and password instead":"Already have an account? Sign in"}</button>{mode==="signin"&&<div className="w-sub-option">◎ Use a passkey or biometric <small>coming soon</small></div>}</div>}
    {screen===2&&<div className="w-screen"><p className="w-kicker">{mode==="signin"?"SECURE SIGN IN":"VERIFY YOUR PHONE"}</p><h1>{mode==="signin"?"Enter your code.":"A code, just for you."}</h1><p>{mode==="signin"?"We sent a 6-digit code to your phone.":"Type the 6-digit SMS code we sent. No health information is needed yet."}</p><div className="w-code">{[1,2,3,4,5,6].map(i=><input key={i} maxLength={1} aria-label={`Digit ${i}`}/>)}</div><p className="w-error">Codes expire after 10 minutes. Resend in 00:42</p><label>Legal name<input placeholder="As it appears on your ID"/></label>{mode==="signup"&&<><label>Preferred name<input placeholder="What should we call you?"/></label><label className="check"><input type="checkbox"/> I accept Wasl’s Terms and Privacy Policy.</label><label className="check"><input type="checkbox"/> I expressly consent to processing sensitive care information.</label></>}<button className="w-primary" onClick={()=>go(3)}>Continue <span>→</span></button></div>}
    {screen===3&&<div className="w-screen"><p className="w-kicker">YOUR PLACE IN THE CIRCLE</p><h1>How will you<br/>use Wasl?</h1><p>We use this to show the right tools. You can change details later.</p><div className="w-role-list">{roles.map(r=><button key={r.name} className={role===r.name?"selected":""} onClick={()=>setRole(r.name)}><span className="w-radio"/><div><b>{r.name}</b><small>{r.desc}</small><em>{r.detail}</em></div></button>)}</div><button className="w-primary" onClick={()=>go(4)}>Continue <span>→</span></button></div>}
    {screen===4&&<div className="w-screen"><p className="w-kicker">CIRCLE PATH</p><h1>Start new or<br/>join an invitation?</h1><p>{role==="Circle Lead"?"Circle Leads usually start a new Wasl Circle.":"Most trusted partners join with a code or link."}</p><div className="w-choice selected"><b>＋ Set up a new Wasl Circle</b><small>Name your circle, then invite trusted people now or later.</small></div><div className="w-choice"><b>⌁ Join with an invitation</b><small>You’ll preview the inviter, role, and exact data shared before accepting.</small></div><label>Circle name<input value={circle} onChange={e=>setCircle(e.target.value)}/></label><button className="w-primary" onClick={()=>go(5)}>Continue <span>→</span></button></div>}
    {screen===5&&<div className="w-screen"><p className="w-kicker">MAKE WASL YOURS</p><h1>How should we<br/>speak to you?</h1><p>Small choices help this feel like your space.</p><label>Preferred name<input placeholder="For example, Fatima"/></label><div className="w-mini-grid"><button className="selected">Salam-based</button><button>Neutral</button><button>Name only</button><button>Custom</button></div><label>Preferred language<select><option>{lang}</option><option>Français</option><option>العربية</option><option>فارسی</option></select></label><p className="w-fine">Pronouns are optional. You can edit these choices anytime.</p><button className="w-primary" onClick={()=>go(role==="Circle Lead"?6:7)}>Continue <span>→</span></button></div>}
    {screen===6&&<div className="w-screen"><p className="w-kicker">WHAT MATTERS TO ME · OPTIONAL</p><h1>Your preferences<br/>belong here.</h1><p>Share only what feels useful. Nothing diagnoses you, and you can choose “Prefer not to answer.”</p><div className="w-list-check"><label><input type="checkbox"/> Halal / dietary preferences</label><label><input type="checkbox"/> Prayer reminders and method</label><label><input type="checkbox"/> Community interests</label><label><input type="checkbox"/> Communication style</label><label><input type="checkbox"/> Same-gender care by task</label></div><div className="w-note">Only relevant preferences travel with a task. Edit anytime.</div><button className="w-primary" onClick={()=>go(7)}>Continue <span>→</span></button><button className="w-skip" onClick={()=>go(7)}>Skip optional questions</button></div>}
    {screen===7&&<div className="w-screen"><p className="w-kicker">SAFETY & COMFORT</p><h1>Let’s make this<br/>comfortable.</h1><p>Choose what helps you use Wasl. Emergency contact is optional, but recommended.</p><div className="w-mini-grid"><button className="selected">Standard text</button><button>Large text</button><button>Extra large</button><button>Reduced motion</button></div><label>Emergency contact<input placeholder="Name, relationship, phone (optional)"/></label><div className="w-note">Wasl coordinates care and reminders. It does not provide medical advice or emergency response.</div><button className="w-primary" onClick={()=>go(8)}>Continue <span>→</span></button></div>}
    {screen===8&&<div className="w-screen"><p className="w-kicker">YOUR RHYTHM</p><h1>Choose your<br/>notifications.</h1><p>Push permission comes only after you choose Push.</p><div className="w-list-check"><label><input type="checkbox" defaultChecked/> In-app</label><label><input type="checkbox"/> Push</label><label><input type="checkbox"/> SMS</label><label><input type="checkbox"/> Email</label></div><div className="w-notify-card"><b>What would you like to hear about?</b><span>Prayer times · Alerts · Reminders · Arrivals / pickups · Circle messages · Daily summary</span><small>Quiet hours can be set next. Urgent alerts override quiet hours only with your explicit choice.</small></div><button className="w-primary" onClick={()=>go(9)}>Continue <span>→</span></button><button className="w-skip" onClick={()=>go(9)}>Skip for now</button></div>}
    {screen===9&&<div className="w-screen"><p className="w-kicker">READY WHEN YOU ARE</p><h1>Review your<br/>choices.</h1><p>Nothing is hidden. Edit any group before you finish.</p>{["Account · phone verified","Circle · "+circle,"Preferences · 4 choices","Availability · not set","Notifications · In-app","Permissions · assigned tasks only","Optional connections · wearable skipped"].map(x=><button className="w-review" key={x}><span>{x}</span><b>Edit</b></button>)}<button className="w-primary" onClick={()=>setDone(true)}>Finish setup <span>→</span></button><p className="w-fine center">Autosaved · You can resume later · Back is always available</p></div>}
  </Phone></div>;
}
function Phone({children}:{children:React.ReactNode}) { return <div className="w-proto-frame"><div className="w-phone"><div className="w-notch"/><div className="w-phone-body">{children}</div></div><div className="w-proto-caption"><b>INTERACTIVE PROTOTYPE</b><span>Tap through the elder-friendly path · {screens.length} representative screens</span></div></div> }
export default InteractiveFlow;